<a href="https://colab.research.google.com/github/jude-craft/ml-playground/blob/main/ML_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

melbourne_file_path = '/content/drive/MyDrive/Data Science/Datasets/melb_data.csv'
df = pd.read_csv(melbourne_file_path)
df.columns
# df = df.dropna(axis=0)

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [4]:
y = df.Price
features = ['Rooms','Bathroom','Landsize','BuildingArea',
                        'YearBuilt','Lattitude','Longtitude']
X = df[features]

X.describe()

,Rooms,Bathroom,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude
count,13580.000000,13580.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000
mean,2.937997,1.534242,558.416127,151.967650,1964.684217,-37.809203,144.995216
std,0.955748,0.691712,3990.669241,541.014538,37.273762,0.079260,0.103916
min,1.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810
25%,2.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600
50%,3.000000,1.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100
75%,3.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305
max,10.000000,8.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350

In [5]:
X.head()

   Rooms  Bathroom  Landsize  BuildingArea  YearBuilt  Lattitude  Longtitude
0      2       1.0     202.0           NaN        NaN   -37.7996    144.9984
1      2       1.0     156.0          79.0     1900.0   -37.8079    144.9934
2      3       2.0     134.0         150.0     1900.0   -37.8093    144.9944
3      3       2.0      94.0           NaN        NaN   -37.7969    144.9969
4      4       1.0     120.0         142.0     2014.0   -37.8072    144.9941

In [6]:
from sklearn.tree import DecisionTreeRegressor

melbourne_model = DecisionTreeRegressor(random_state=1)

melbourne_model.fit(X,y)

DecisionTreeRegressor(random_state=1)

In [7]:
print("Making predictions for the following 5 houses:")
print(X)
print("The predictions are:")
print(melbourne_model.predict(X))

Making predictions for the following 5 houses:
       Rooms  Bathroom  Landsize  BuildingArea  YearBuilt  Lattitude  \
0          2       1.0     202.0           NaN        NaN  -37.79960
1          2       1.0     156.0          79.0     1900.0  -37.80790
2          3       2.0     134.0         150.0     1900.0  -37.80930
3          3       2.0      94.0           NaN        NaN  -37.79690
4          4       1.0     120.0         142.0     2014.0  -37.80720
...      ...       ...       ...           ...        ...        ...
13575      4       2.0     652.0           NaN     1981.0  -37.90562
13576      3       2.0     333.0         133.0     1995.0  -37.85927
13577      3       2.0     436.0           NaN     1997.0  -37.85274
13578      4       1.0     866.0         157.0     1920.0  -37.85908
13579      4       1.0     362.0         112.0     1920.0  -37.81188

       Longtitude
0       144.99840
1       144.99340
2       144.99440
3       144.99690
4       144.99410
...           ...
13575   145.16761
13576   144.87904
13577   144.88738
13578   144.89299
13579   144.88449

[13580 rows x 7 columns]
The predictions are:
[1480000. 1035000. 1465000. ... 1170000. 2500000. 1285000.]

# Model Validation #

In [ ]:
# How to calculate mean_absolute_error
from sklearn.metrics import mean_absolute_error
predicted_home_prices = melbourne_model.predict(X)
mean_absolute_error(y,predicted_home_prices)   # in-sample - not recommended, very inaccurate when used in practice

4742.169857633775

In [9]:
from sklearn.model_selection import train_test_split
# split data into training and validation data, for both features and target
train_X, val_X, train_y, val_y = train_test_split(X,y,random_state=0)

melbourne_model = DecisionTreeRegressor()
melbourne_model.fit(train_X,train_y)

val_predictions = melbourne_model.predict(val_X)
print(mean_absolute_error(val_y,val_predictions))

248764.09327442318

# Random Forest #

In [10]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

forest_model = RandomForestRegressor(random_state=1)
forest_model.fit(train_X,train_y)
melb_preds = forest_model.predict(val_X)
print(mean_absolute_error(val_y, melb_preds))

176805.75068728524